-- Insert initial products
INSERT INTO public.products (id, category, sub_category, gender, sizes, image, accent_glow, accent_color, ar_name, ar_collection, ar_short_desc, ar_desc, ar_spec_left, ar_spec_right, ar_price, ar_mood, en_name, en_collection, en_short_desc, en_desc, en_spec_left, en_spec_right, en_price, en_mood) VALUES
('jasmine', 'perfumes', 'original', 'women', null, 'assets/images/product_jasmine.png', 'rgba(237, 224, 200, 0.15)', '#EDE0C8', 
'ذاكرة الفل', 'مجموعة الماضي الجميل', 'رقة الفل والياسمين البلدي في بيوت القاهرة القديمة بمشربياتها العتيقة.', 'نفحات عطرية تصحبك لبيوت القاهرة القديمة بمشربياتها الخشبية العتيقة وحدائقها المليئة بالفل والياسمين البري مع نسيم الليل الهادئ. عطر يحاكي براءة ونقاء أيام الطفولة.', 'فل بلدي، ياسمين جبلي، زنبق الوادي', 'خشب الصندل الدافئ، مسك أبيض ناعم', '٤٥٠ جنيه', 'دافئ، رومانسي، ناعم',
'Jasmine Memory', 'Vintage Past Collection', 'The delicacy of local jasmine in ancient Cairo houses with antique mashrabiyas.', 'Aromatic notes accompanying you to Cairo''s old houses with vintage wooden mashrabiyas and gardens blooming with local jasmine in the quiet night breeze. A scent mimicking childhood innocence.', 'Local Jasmine, Mountain Jasmine, Lily of the Valley', 'Warm Sandalwood, Soft White Musk', '450 EGP', 'Warm, Romantic, Soft'),

('oud', 'perfumes', 'inspired', 'unisex', null, 'assets/images/product_oud.png', 'rgba(201, 168, 76, 0.2)', '#C9A84C',
'سر العود', 'مجموعة التراث المعتق', 'بخور العود الفخم مع توابل وبزارات الحسين التاريخية المعتقة.', 'عطر مهيب مستوحى من أبخرة النحاس المشتعل بالعود الفاخر في بازارات الحسين التاريخية. مزيج ساحر يمنحك حضوراً واثقاً وغامضاً يعود بك لقرون مضت.', 'زعفران ناري، دارسين (قرفة)، هيل بري', 'عود ملكي معتق، خشب الأرز، لبان مسك', '٥٥٠ جنيه', 'غامض، فخم، مهيب',
'Oud Secret', 'Aged Heritage Collection', 'Premium oud incense blended with historical Hussein aged spices and bazaars.', 'A majestic fragrance inspired by copper burner vapors of luxurious oud in the historical bazaars of El Hussein. A magical blend giving you a confident, mysterious presence going back centuries.', 'Fiery Saffron, Cinnamon, Wild Cardamom', 'Royal Aged Oud, Cedarwood, Musk Frankincense', '550 EGP', 'Mysterious, Luxurious, Majestic'),

('khedive', 'perfumes', 'original', 'men', null, 'assets/images/product_oud.png', 'rgba(201, 168, 76, 0.2)', '#C9A84C',
'الخديوي', 'مجموعة العظمة والتفرد', 'وقار الجلود مع حدة التبغ والقهوة العربية الفاخرة.', 'عطر رجالي مهيب يعبر عن الهيبة والوقار، يفتتح بلمسة برغموت دافئة تليها نبضات الجلود والتوابل الحارة، وتستقر قاعدته على سحر التبغ والقهوة والمسك المعتق.', 'برغموت إيطالي، قهوة عربية، هيل', 'جلود فاخرة، تبغ خام، خشب الصندل', '٥٩٠ جنيه', 'رجولي، مهيب، حاد',
'The Khedive', 'Grandeur & Distinction Collection', 'The prestige of leather with the boldness of raw tobacco and fine Arabic coffee.', 'A majestic masculine scent expressing authority and stature, opening with warm bergamot and dry cardamom, leading to a heart of leather, settling on raw tobacco, coffee, and aged musk.', 'Italian Bergamot, Arabic Coffee, Cardamom', 'Premium Leather, Raw Tobacco, Sandalwood', '590 EGP', 'Masculine, Majestic, Bold'),

('cairo-rose', 'perfumes', 'inspired', 'women', null, 'assets/images/product_nostalgia.png', 'rgba(123, 45, 62, 0.25)', '#7B2D3E',
'وردة القاهرة', 'مجموعة رقة المساء', 'نعومة الورد الطائفي الممزوج مع المسك الأبيض وخشب الكشمير.', 'توليفة رقيقة وجذابة تحتفي بالأنوثة الكلاسيكية والجمال الهادئ. نفحات الورد الطائفي الطبيعي الممتزج مع المسك السكري الفاخر ونعومة خشب الكشمير.', 'ورد طائفي، توت العليق، ياسمين ناعم', 'مسك سكري، خشب الكشمير، فانيليا دافئة', '٤٨٠ جنيه', 'أنثوي، رقيق، جذاب',
'Cairo Rose', 'Evening Delicacy Collection', 'The softness of Taif rose blended with premium white musk and cashmere wood.', 'A delicate and attractive blend celebrating classic femininity and serene beauty. Fresh notes of natural Taif rose mixed with luxurious sweet musk and cashmere wood.', 'Taif Rose, Raspberry, Soft Jasmine', 'Sweet Musk, Cashmere Wood, Warm Vanilla', '480 EGP', 'Feminine, Delicate, Attractive'),

('nostalgia', 'perfumes', 'recreated', 'women', null, 'assets/images/product_nostalgia.png', 'rgba(123, 45, 62, 0.25)', '#7B2D3E',
'عبير النوستالجيا', 'مجموعة الحنين الفاخرة', 'ورد مجفف وعنبر دافئ يجسدان صندوق ذكريات الحب الرائعة.', 'توليفة مخملية تجسد ذكريات الحب الرائعة المكتوبة برائحة الورد المجفف وأحجار العنبر الدافئة المنسكبة في صندوق خشبي قديم. يمنحك طاقة دفء تدوم طويلاً.', 'ورد جوري أحمر، زهر البرتقال، توت بري', 'عنبر خام، باتشولي دافئ، فانيليا معتقة', '٤٩٠ جنيه', 'مخملي، جذاب، عميق',
'Nostalgia Breeze', 'Luxury Nostalgia Collection', 'Dried roses and warm amber embodying a box of wonderful love memories.', 'A velvety blend embodying wonderful love memories written in the scent of dried roses and warm amber stones stored in an old wooden box. Gives you a long-lasting warm energy.', 'Red Damask Rose, Orange Blossom, Wild Berries', 'Raw Amber, Warm Patchouli, Vintage Vanilla', '490 EGP', 'Velvety, Attractive, Deep'),

('linen-shirt', 'clothes', null, 'men', '["S", "M", "L", "XL", "XXL"]', 'assets/images/product_jasmine.png', 'rgba(237, 224, 200, 0.15)', '#EDE0C8',
'قميص كتان راقي', 'مجموعة الصيف الفاخرة', 'قميص كتان إيطالي ناعم وبارد بتفاصيل خياطة يدوية راقية.', 'قميص صيفي كلاسيكي عصري مصنوع من خامة الكتان الطبيعي الفاخر بنسبة 100%. يتميز بقصة مريحة وأنيقة تناسب الإطلالات اليومية الذكية في الطقس الدافئ.', 'كتان إيطالي نقي 100% فائق النعومة', 'قصة مريحة (Slim/Regular) خياطة وتطريز يدوي دقيق', '٨٥٠ جنيه', null,
'Premium Linen Shirt', 'Luxury Summer Collection', 'Breathable and soft Italian linen shirt with minimalist stitching.', 'A classic-modern summer shirt tailored from 100% pure premium natural linen. Features a relaxed yet structured fit perfect for smart casual outings.', '100% Pure Ultra-Soft Italian Linen', 'Comfortable Slim/Regular Cut, fine manual tailoring', '850 EGP', null),

('linen-dress', 'clothes', null, 'women', '["XS", "S", "M", "L", "XL"]', 'assets/images/story_bg.png', 'rgba(237, 224, 200, 0.15)', '#EDE0C8',
'فستان كتان راقي', 'مجموعة الصيف الفاخرة', 'فستان صيفي رقيق مصنوع من ألياف الكتان الطبيعية لتمنحك الأناقة والانتعاش.', 'فستان نسائي صيفي كلاسيكي رقيق مصنوع من خامة الكتان الطبيعي الفاخر بنسبة 100%. تصميم مريح وأنيق يجمع البساطة الراقية ومناسب لإطلالة مسائية مميزة.', 'كتان نقي 100% طبيعي وناعم', 'قصة مريحة كلاسيكية، تطريز يدوي على الأكمام والياقة', '١٤٠٠ جنيه', null,
'Premium Linen Dress', 'Luxury Summer Collection', 'Delicate summer dress crafted from premium natural linen for style and freshness.', 'A classic-modern summer dress tailored from 100% pure premium natural linen. Features a relaxed yet elegant silhouette for outstanding summer evenings.', '100% Pure Breathable Natural Linen', 'Classic relaxed fit, fine handmade embroidery on sleeves', '1,400 EGP', null),

('tailored-trousers', 'clothes', null, 'men', '["30", "32", "34", "36", "38"]', 'assets/images/story_bg.png', 'rgba(201, 168, 76, 0.15)', '#C9A84C',
'بنطال كلاسيكي أنيق', 'مجموعة الأناقة العصرية', 'بنطال صوف خفيف وقصة ممتازة تمنحك إطلالة رسمية ومريحة.', 'بنطال مصمم بعناية فائقة من أقمشة مخلوطة خفيفة الوزن توفر سهولة الحركة مع الحفاظ على الشكل الكلاسيكي المرتب والمثالي للمناسبات الرسمية والعملية.', 'صوف خفيف مخلوط بالقطن العضوي الممتاز', 'قصة مستقيمة كلاسيكية (Straight Fit)، تفاصيل حزام مدمج', '١٢٠٠ جنيه', null,
'Classic Tailored Trousers', 'Modern Elegance Collection', 'Light wool-blend trousers with a refined fit for structured daily style.', 'Meticulously designed pants tailored from light breathable wool and cotton blend. Offers outstanding flexibility while keeping a clean classic outline.', 'Light Wool and Organic Cotton Blend', 'Straight Classic Fit, build-in waist adjusters', '1,200 EGP', null),

('minimalist-sneakers', 'shoes', null, 'unisex', '["40", "41", "42", "43", "44", "45"]', 'assets/images/product_nostalgia.png', 'rgba(123, 45, 62, 0.15)', '#7B2D3E',
'حذاء جلدي عصري', 'مجموعة الخطوات المريحة', 'حذاء رياضي جلدي بسيط ومريح يناسب جميع المناسبات الكاجوال.', 'حذاء رياضي كاجوال مصنع بالكامل من الجلد الطبيعي الممتاز. تصميم بسيط بخطوط نظيفة ونعل مطاطي مريح يناسب الاستخدام اليومي والأناقة العصرية الكاجوال.', 'جلد طبيعي 100% مدبوغ بعناية', 'نعل مطاطي مرن ومبطن، بطانة طبية مريحة', '١٤٥٠ جنيه', null,
'Minimalist Leather Sneakers', 'Comfort Steps Collection', 'Clean and minimalist leather sneakers for smart casual everyday comfort.', 'Sleek low-top sneakers crafted entirely from high-grade natural leather. Minimalist design featuring flexible support ideal for dynamic modern life.', '100% Hand-finished Genuine Leather', 'Flexible rubber sole, orthotic padded inner lining', '1,450 EGP', null),

('classic-flats', 'shoes', null, 'women', '["36", "37", "38", "39", "40", "41"]', 'assets/images/product_jasmine.png', 'rgba(237, 224, 200, 0.15)', '#EDE0C8',
'حذاء فلات كلاسيكي', 'مجموعة الخطوات المريحة', 'حذاء نسائي فلات مصنوع يدوياً من الجلد الطبيعي الناعم والمريح.', 'حذاء نسائي لوفر/فلات كلاسيكي مصنوع يدوياً بالكامل من أجود أنواع الجلود الطبيعية. تصميم أنيق وبسيط يوفر راحة فائقة ومظهر لائق للاستخدام اليومي الممتد.', 'جلد طبيعي ناعم مدبوغ ومطرز يدوياً', 'نعل مطاطي مريح ومرن مع بطانة طبية داخلية مضاعفة', '١٢٥٠ جنيه', null,
'Classic Leather Flats', 'Comfort Steps Collection', 'Handcrafted women''s flats made from soft genuine leather for ultimate comfort.', 'Artisanal women''s flats handcrafted from ultra-soft genuine leather. Stylish minimalist design that ensures cozy support for extended active wear.', '100% Soft Tanned Hand-stitched Leather', 'Flexible rubber outsole, padded orthopedic double-cushioned lining', '1,250 EGP', null),

('leather-loafers', 'shoes', null, 'men', '["40", "41", "42", "43", "44", "45"]', 'assets/images/product_oud.png', 'rgba(201, 168, 76, 0.2)', '#C9A84C',
'حذاء لوفر كلاسيكي', 'مجموعة المناسبات الراقية', 'لوفر جلدي فاخر مصنوع يدوياً ليناسب الإطلالات الكلاسيكية والأنيقة.', 'حذاء لوفر كلاسيكي أنيق مصنع يدوياً من أفخر أنواع الجلود الطبيعية. يوفر راحة تامة للقدمين ومظهرًا فخمًا يليق بالمناسبات والبدل الرسمية والأطقم الكلاسيكية.', 'جلد ماعز طبيعي مدبوغ ومطرز يدوياً بالكامل', 'نعل جلدي معزز بطبقة مطاطية مدمجة لمنع الانزلاق', '١٦٥٠ جنيه', null,
'Classic Leather Loafers', 'Premium Occasions Collection', 'Handcrafted luxury leather loafers for tailored formal and semi-formal looks.', 'Timeless classic leather loafers, handcrafted by skilled artisan shoemakers. Made with soft leather for a custom-fit feel and clean luxurious look.', 'Artisan Tanned Premium Goatskin Leather', 'Stacked premium leather sole with anti-slip grip insert', '1,650 EGP', null);
